//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sklad_bd_lelikov
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_Storage_place
    {
        public int ID_storage_place { get; set; }
        public int ID_product { get; set; }
        public Nullable<int> C_Count { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Storage_place Storage_place { get; set; }
    }
}
